"""Verifies that the Claude Desktop configuration generated by setup.py is correct."""

from __future__ import annotations

import json
import os
import textwrap
from unittest.mock import patch

import pytest


PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class TestConfigureClaudeDesktop:
    """Checks if configure_claude_desktop() registers the server with an absolute path."""

    def test_server_path_is_absolute(self, tmp_path):
        """Checks if the server file path in the generated config is an absolute path."""
        config_path = tmp_path / "claude_desktop_config.json"
        config_path.write_text("{}")

        with (
            patch("setup._get_claude_config_path", return_value=str(config_path)),
            patch("setup.sys") as mock_sys,
        ):
            mock_sys.stdin.isatty.return_value = False

            import setup

            setup.configure_claude_desktop("/usr/bin/uv")

        config = json.loads(config_path.read_text())
        server = config["mcpServers"]["handwriting-ocr-mcp"]
        # Argument after fastmcp run is the server.py path
        server_file_arg = server["args"][-1]  # "/.../server.py:mcp"
        path_part = server_file_arg.split(":")[0]

        assert os.path.isabs(path_part), f"Server path is relative: {path_part}"
        assert path_part.endswith("server.py")

    def test_server_path_points_to_real_file(self, tmp_path):
        """Checks if the server file in the generated config actually exists."""
        config_path = tmp_path / "claude_desktop_config.json"
        config_path.write_text("{}")

        with (
            patch("setup._get_claude_config_path", return_value=str(config_path)),
            patch("setup.sys") as mock_sys,
        ):
            mock_sys.stdin.isatty.return_value = False

            import setup

            setup.configure_claude_desktop("/usr/bin/uv")

        config = json.loads(config_path.read_text())
        server_file_arg = config["mcpServers"]["handwriting-ocr-mcp"]["args"][-1]
        path_part = server_file_arg.split(":")[0]

        assert os.path.exists(path_part), f"Server file does not exist: {path_part}"
